### ISSUE TITLE
springboot整合打包成功后，运行提示sum/misc/URLClassPath找不到

### ISSUE THREAD

**Issue by jiangchengshi** [core-lib/xjar-maven-plugin#6]
1、xjar：2.1.1；jdk：11；spring boot：2.1.2.RELEASE；
2、maven完成打包；
3、运行 java -jar ./xxx.xjar；
4、输入密码，提示错误

![image](https://user-images.githubusercontent.com/21210629/79191556-76e30500-7e59-11ea-9adc-20ff0ded6c25.png)

**Comment by jiangchengshi** [comment]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.xjar.boot.XBootClassLoader (file:/E:/wechat-0.0.1-SNAPSHOT.xjar) to field java.net.URLClassLoader.ucp
WARNING: Please consider reporting this to the maintainers of io.xjar.boot.XBootClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/URLClassPath
        at io.xjar.boot.XBootClassLoader.<init>(XBootClassLoader.java:40)
        at io.xjar.boot.XJarLauncher.createClassLoader(XJarLauncher.java:31)
        at org.springframework.boot.loader.Launcher.createClassLoader(Launcher.java:64)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at io.xjar.boot.XJarLauncher.launch(XJarLauncher.java:26)
        at io.xjar.boot.XJarLauncher.main(XJarLauncher.java:22)
Caused by: java.lang.ClassNotFoundException: sun.misc.URLClassPath
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more

**Comment by eric2877** [comment]
同样的问题，应该是需要使用生成的go启动器有关系，希望作者尽快给个说明文档，之前2.0.6用的正常。
另外什么是时候能够实现加密密码和启动密码分开？
